# Pandas Basics Exploration

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 100)

## 1. Create Series and DataFrames

In [3]:
scores = pd.Series([88, 91, 76, 95], index=['Asha', 'Ben', 'Chirag', 'Diya'])
scores

Asha      88
Ben       91
Chirag    76
Diya      95
dtype: int64

In [4]:
student_data = {
    'name': ['Asha', 'Ben', 'Chirag', 'Diya', 'Esha'],
    'age': [20, 21, 19, 22, 20],
    'marks': [88, 91, 76, 95, np.nan],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Delhi']
}

df = pd.DataFrame(student_data)
df

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

## 2. Inspect the data

In [5]:
df.head()

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

In [6]:
df.tail()

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

In [7]:
df.shape, df.columns, df.index

((5, 4),
 Index(['name', 'age', 'marks', 'city'], dtype='object'),
 RangeIndex(start=0, stop=5, step=1))

In [8]:
df.dtypes

name      object
age        int64
marks    float64
city      object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   marks   4 non-null      float64
 3   city    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes

In [10]:
df.describe(include='all')

        name        age      marks   city
count      5   5.000000   4.000000      5
unique     5        NaN        NaN      3
top     Asha        NaN        NaN  Delhi
freq       1        NaN        NaN      3
mean     NaN  20.400000  87.500000    NaN
std      NaN   1.140175   8.185353    NaN
min      NaN  19.000000  76.000000    NaN
25%      NaN  20.000000  85.000000    NaN
50%      NaN  20.000000  89.500000    NaN
75%      NaN  21.000000  92.000000    NaN
max      NaN  22.000000  95.000000    NaN

## 3. Select rows and columns

In [11]:
df['name']

0      Asha
1       Ben
2    Chirag
3      Diya
4      Esha
Name: name, dtype: object

In [12]:
df[['name', 'marks']]

     name  marks
0    Asha   88.0
1     Ben   91.0
2  Chirag   76.0
3    Diya   95.0
4    Esha    NaN

In [13]:
df.loc[1:3, ['name', 'city']]

     name     city
1     Ben   Mumbai
2  Chirag    Delhi
3    Diya  Chennai

In [14]:
df.iloc[0:3, 0:2]

     name  age
0    Asha   20
1     Ben   21
2  Chirag   19

In [15]:
df[df['marks'] > 85]

   name  age  marks     city
0  Asha   20   88.0    Delhi
1   Ben   21   91.0   Mumbai
3  Diya   22   95.0  Chennai

In [16]:
df[(df['city'] == 'Delhi') & (df['marks'] > 80)]

   name  age  marks   city
0  Asha   20   88.0  Delhi

## 4. Clean missing values

In [17]:
df.isna()

    name    age  marks   city
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False   True  False

In [18]:
df.fillna({'marks': df['marks'].mean()})

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20   87.5    Delhi

In [19]:
df.dropna()

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai

## 5. Sort, rename, and transform

In [20]:
df.sort_values(by='marks', ascending=False)

     name  age  marks     city
3    Diya   22   95.0  Chennai
1     Ben   21   91.0   Mumbai
0    Asha   20   88.0    Delhi
2  Chirag   19   76.0    Delhi
4    Esha   20    NaN    Delhi

In [21]:
df.rename(columns={'marks': 'score'})

     name  age  score     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

In [22]:
df.drop(columns=['city'])

     name  age  marks
0    Asha   20   88.0
1     Ben   21   91.0
2  Chirag   19   76.0
3    Diya   22   95.0
4    Esha   20    NaN

In [23]:
df['marks_plus_5'] = df['marks'] + 5
df['passed'] = df['marks'] >= 80
df

     name  age  marks     city  marks_plus_5  passed
0    Asha   20   88.0    Delhi          93.0    True
1     Ben   21   91.0   Mumbai          96.0    True
2  Chirag   19   76.0    Delhi          81.0   False
3    Diya   22   95.0  Chennai         100.0    True
4    Esha   20    NaN    Delhi           NaN   False

In [24]:
df['city'].value_counts()

city
Delhi      3
Mumbai     1
Chennai    1
Name: count, dtype: int64

## 6. Group by and aggregate

In [25]:
df.groupby('city')['marks'].mean()

city
Chennai    95.0
Delhi      82.0
Mumbai     91.0
Name: marks, dtype: float64

In [26]:
df.groupby('city').agg({'marks': ['mean', 'max', 'min'], 'age': 'count'})

        marks               age
         mean   max   min count
city
Chennai  95.0  95.0  95.0     1
Delhi    82.0  88.0  76.0     3
Mumbai   91.0  91.0  91.0     1

## 7. Combine DataFrames

In [27]:
left = pd.DataFrame({'student_id': [1, 2, 3], 'name': ['Asha', 'Ben', 'Chirag']})
right = pd.DataFrame({'student_id': [1, 2, 3], 'course': ['Python', 'SQL', 'Pandas']})

pd.merge(left, right, on='student_id')

   student_id    name  course
0           1    Asha  Python
1           2     Ben     SQL
2           3  Chirag  Pandas

In [28]:
first_half = df.head(2)
second_half = df.tail(2)
pd.concat([first_half, second_half], ignore_index=True)

   name  age  marks     city  marks_plus_5  passed
0  Asha   20   88.0    Delhi          93.0    True
1   Ben   21   91.0   Mumbai          96.0    True
2  Diya   22   95.0  Chennai         100.0    True
3  Esha   20    NaN    Delhi           NaN   False

## 8. Read and write data

In [29]:
csv_text = df.to_csv(index=False)
from io import StringIO

round_trip = pd.read_csv(StringIO(csv_text))
round_trip

     name  age  marks     city  marks_plus_5  passed
0    Asha   20   88.0    Delhi          93.0    True
1     Ben   21   91.0   Mumbai          96.0    True
2  Chirag   19   76.0    Delhi          81.0   False
3    Diya   22   95.0  Chennai         100.0    True
4    Esha   20    NaN    Delhi           NaN   False

## 9. Extra useful basics

In [30]:
df['city'].unique(), df['city'].nunique()

(array(['Delhi', 'Mumbai', 'Chennai'], dtype=object), 3)

In [31]:
df.sample(3, random_state=42)

     name  age  marks    city  marks_plus_5  passed
1     Ben   21   91.0  Mumbai          96.0    True
4    Esha   20    NaN   Delhi           NaN   False
2  Chirag   19   76.0   Delhi          81.0   False

In [32]:
df_copy = df.copy()
df_copy['marks'] = df_copy['marks'].astype('float')
df_copy['name_upper'] = df_copy['name'].apply(str.upper)
df_copy

     name  age  marks     city  marks_plus_5  passed name_upper
0    Asha   20   88.0    Delhi          93.0    True       ASHA
1     Ben   21   91.0   Mumbai          96.0    True        BEN
2  Chirag   19   76.0    Delhi          81.0   False     CHIRAG
3    Diya   22   95.0  Chennai         100.0    True       DIYA
4    Esha   20    NaN    Delhi           NaN   False       ESHA