# Pandas Basics Exploration

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 100)

## 1. Create Series and DataFrames

In [4]:
scores = pd.Series([88, 91, 76, 95], index=['Asha', 'Ben', 'Chirag', 'Diya'])
scores

Asha      88
Ben       91
Chirag    76
Diya      95
dtype: int64

In [4]:
student_data = {
    'name': ['Asha', 'Ben', 'Chirag', 'Diya', 'Esha'],
    'age': [20, 21, 19, 22, 20],
    'marks': [88, 91, 76, 95, np.nan],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Delhi']
}

df = pd.DataFrame(student_data)
df

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

## 2. Inspect the data

In [5]:
df.head()

NameError: name 'df' is not defined

In [6]:
df.tail()

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

In [6]:
df.shape, df.columns, df.index

NameError: name 'df' is not defined

In [8]:
df.dtypes

name      object
age        int64
marks    float64
city      object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   marks   4 non-null      float64
 3   city    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes

In [10]:
df.describe(include='all')

        name        age      marks   city
count      5   5.000000   4.000000      5
unique     5        NaN        NaN      3
top     Asha        NaN        NaN  Delhi
freq       1        NaN        NaN      3
mean     NaN  20.400000  87.500000    NaN
std      NaN   1.140175   8.185353    NaN
min      NaN  19.000000  76.000000    NaN
25%      NaN  20.000000  85.000000    NaN
50%      NaN  20.000000  89.500000    NaN
75%      NaN  21.000000  92.000000    NaN
max      NaN  22.000000  95.000000    NaN

## 3. Select rows and columns

In [11]:
df['name']

0      Asha
1       Ben
2    Chirag
3      Diya
4      Esha
Name: name, dtype: object

In [12]:
df[['name', 'marks']]

     name  marks
0    Asha   88.0
1     Ben   91.0
2  Chirag   76.0
3    Diya   95.0
4    Esha    NaN

In [13]:
df.loc[1:3, ['name', 'city']]

     name     city
1     Ben   Mumbai
2  Chirag    Delhi
3    Diya  Chennai

In [14]:
df.iloc[0:3, 0:2]

     name  age
0    Asha   20
1     Ben   21
2  Chirag   19

In [15]:
df[df['marks'] > 85]

   name  age  marks     city
0  Asha   20   88.0    Delhi
1   Ben   21   91.0   Mumbai
3  Diya   22   95.0  Chennai

In [16]:
df[(df['city'] == 'Delhi') & (df['marks'] > 80)]

   name  age  marks   city
0  Asha   20   88.0  Delhi

## 4. Clean missing values

In [17]:
df.isna()

    name    age  marks   city
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False   True  False

In [18]:
df.fillna({'marks': df['marks'].mean()})

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20   87.5    Delhi

In [19]:
df.dropna()

     name  age  marks     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai

## 5. Sort, rename, and transform

In [20]:
df.sort_values(by='marks', ascending=False)

     name  age  marks     city
3    Diya   22   95.0  Chennai
1     Ben   21   91.0   Mumbai
0    Asha   20   88.0    Delhi
2  Chirag   19   76.0    Delhi
4    Esha   20    NaN    Delhi

In [21]:
df.rename(columns={'marks': 'score'})

     name  age  score     city
0    Asha   20   88.0    Delhi
1     Ben   21   91.0   Mumbai
2  Chirag   19   76.0    Delhi
3    Diya   22   95.0  Chennai
4    Esha   20    NaN    Delhi

In [22]:
df.drop(columns=['city'])

     name  age  marks
0    Asha   20   88.0
1     Ben   21   91.0
2  Chirag   19   76.0
3    Diya   22   95.0
4    Esha   20    NaN

In [23]:
df['marks_plus_5'] = df['marks'] + 5
df['passed'] = df['marks'] >= 80
df

     name  age  marks     city  marks_plus_5  passed
0    Asha   20   88.0    Delhi          93.0    True
1     Ben   21   91.0   Mumbai          96.0    True
2  Chirag   19   76.0    Delhi          81.0   False
3    Diya   22   95.0  Chennai         100.0    True
4    Esha   20    NaN    Delhi           NaN   False

In [24]:
df['city'].value_counts()

city
Delhi      3
Mumbai     1
Chennai    1
Name: count, dtype: int64

## 6. Group by and aggregate

In [25]:
df.groupby('city')['marks'].mean()

city
Chennai    95.0
Delhi      82.0
Mumbai     91.0
Name: marks, dtype: float64

In [26]:
df.groupby('city').agg({'marks': ['mean', 'max', 'min'], 'age': 'count'})

        marks               age
         mean   max   min count
city
Chennai  95.0  95.0  95.0     1
Delhi    82.0  88.0  76.0     3
Mumbai   91.0  91.0  91.0     1

## 7. Combine DataFrames

In [27]:
left = pd.DataFrame({'student_id': [1, 2, 3], 'name': ['Asha', 'Ben', 'Chirag']})
right = pd.DataFrame({'student_id': [1, 2, 3], 'course': ['Python', 'SQL', 'Pandas']})

pd.merge(left, right, on='student_id')

   student_id    name  course
0           1    Asha  Python
1           2     Ben     SQL
2           3  Chirag  Pandas

In [28]:
first_half = df.head(2)
second_half = df.tail(2)
pd.concat([first_half, second_half], ignore_index=True)

   name  age  marks     city  marks_plus_5  passed
0  Asha   20   88.0    Delhi          93.0    True
1   Ben   21   91.0   Mumbai          96.0    True
2  Diya   22   95.0  Chennai         100.0    True
3  Esha   20    NaN    Delhi           NaN   False

## 8. Read and write data

In [29]:
csv_text = df.to_csv(index=False)
from io import StringIO

round_trip = pd.read_csv(StringIO(csv_text))
round_trip

     name  age  marks     city  marks_plus_5  passed
0    Asha   20   88.0    Delhi          93.0    True
1     Ben   21   91.0   Mumbai          96.0    True
2  Chirag   19   76.0    Delhi          81.0   False
3    Diya   22   95.0  Chennai         100.0    True
4    Esha   20    NaN    Delhi           NaN   False

## 9. Extra useful basics

In [30]:
df['city'].unique(), df['city'].nunique()

(array(['Delhi', 'Mumbai', 'Chennai'], dtype=object), 3)

In [31]:
df.sample(3, random_state=42)

     name  age  marks    city  marks_plus_5  passed
1     Ben   21   91.0  Mumbai          96.0    True
4    Esha   20    NaN   Delhi           NaN   False
2  Chirag   19   76.0   Delhi          81.0   False

In [32]:
df_copy = df.copy()
df_copy['marks'] = df_copy['marks'].astype('float')
df_copy['name_upper'] = df_copy['name'].apply(str.upper)
df_copy

     name  age  marks     city  marks_plus_5  passed name_upper
0    Asha   20   88.0    Delhi          93.0    True       ASHA
1     Ben   21   91.0   Mumbai          96.0    True        BEN
2  Chirag   19   76.0    Delhi          81.0   False     CHIRAG
3    Diya   22   95.0  Chennai         100.0    True       DIYA
4    Esha   20    NaN    Delhi           NaN   False       ESHA

## 10. Real dataset: Iris

This section uses the Iris CSV stored in the workspace to demonstrate common pandas operations on a real dataset.

In [2]:
import pandas as pd
from pathlib import Path
from IPython.display import display

candidate_paths = [
    Path('python_programs/15-04-26/data/iris.csv'),
    Path('../15-04-26/data/iris.csv'),
    Path('../../python_programs/15-04-26/data/iris.csv'),
]

iris_path = None
for candidate in candidate_paths:
    if candidate.exists():
        iris_path = candidate
        break

if iris_path is None:
    raise FileNotFoundError('Could not locate iris.csv in the workspace.')

iris = pd.read_csv(
    iris_path,
    header=None,
    names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
)

print(f'Loaded dataset from: {iris_path}')
print('Shape:', iris.shape)
print('Columns:', list(iris.columns))

print('\nHead:')
display(iris.head())

print('\nTail:')
display(iris.tail())

print('\nData types:')
display(iris.dtypes.to_frame('dtype'))

print('\nMissing values:')
display(iris.isna().sum().to_frame('missing_count'))

print('\nDescriptive statistics:')
display(iris.describe())

print('\nSpecies counts:')
display(iris['species'].value_counts())

print('\nAverage measurements by species:')
display(iris.groupby('species').mean(numeric_only=True))

print('\nTop 5 rows by petal length:')
display(iris.sort_values('petal_length', ascending=False).head())

iris['sepal_area'] = iris['sepal_length'] * iris['sepal_width']

print('\nTop 5 rows by sepal area:')
display(iris.nlargest(5, 'sepal_area'))

print('\nCorrelation matrix for numeric columns:')
display(iris.select_dtypes(include='number').corr())

print('\nRandom sample:')
display(iris.sample(5, random_state=42))

Loaded dataset from: ..\15-04-26\data\iris.csv
Shape: (150, 5)
Columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

Head:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Tail:

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

Data types:

                dtype
sepal_length  float64
sepal_width   float64
petal_length  float64
petal_width   float64
species        object

Missing values:

              missing_count
sepal_length              0
sepal_width               0
petal_length              0
petal_width               0
species                   0

Descriptive statistics:

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

Species counts:

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

Average measurements by species:

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

Top 5 rows by petal length:

     sepal_length  sepal_width  petal_length  petal_width         species
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica

Top 5 rows by sepal area:

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
131,7.9,3.8,6.4,2.0,Iris-virginica,30.02
117,7.7,3.8,6.7,2.2,Iris-virginica,29.26
109,7.2,3.6,6.1,2.5,Iris-virginica,25.92
15,5.7,4.4,1.5,0.4,Iris-setosa,25.08
14,5.8,4.0,1.2,0.2,Iris-setosa,23.20

Correlation matrix for numeric columns:

              sepal_length  sepal_width  petal_length  petal_width  sepal_area
sepal_length      1.000000    -0.109369      0.871754     0.817954    0.683362
sepal_width      -0.109369     1.000000     -0.420516    -0.356544    0.645421
petal_length      0.871754    -0.420516      1.000000     0.962757    0.366584
petal_width       0.817954    -0.356544      0.962757     1.000000    0.375365
sepal_area        0.683362     0.645421      0.366584     0.375365    1.000000

Random sample:

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_area
73,6.1,2.8,4.7,1.2,Iris-versicolor,17.08
18,5.7,3.8,1.7,0.3,Iris-setosa,21.66
118,7.7,2.6,6.9,2.3,Iris-virginica,20.02
78,6.0,2.9,4.5,1.5,Iris-versicolor,17.40
76,6.8,2.8,4.8,1.4,Iris-versicolor,19.04